package com.example.learntocode.models.enums;

public enum DotEnv {
    PORT,
    OKTA_OAUTH2_ISSUER,
    OKTA_OAUTH2_AUDIENCE,
    OKTA_OAUTH2_CLIENT_ID,
    OKTA_OAUTH2_CLIENT_SECRET,
    OKTA_OAUTH2_MANAGEMENT_API_TOKEN,
    SPRING_DATASOURCE_URL,
    JDBC_DATABASE_USERNAME,
    JDBC_DATABASE_PASSWORD,
    OPENAI_TOKEN,
    STRIPE_PK,
    STRIPE_SK,
    WEATHER_API_KEY,
    CHATENGINE_PROJECT_ID,
    CHATENGINE_API_KEY
}
