package com.example.learntocode.models.enums;

public enum DotEnv {
    PORT,
    CLIENT_ORIGIN_URL,
    OKTA_OAUTH2_ISSUER,
    OKTA_OAUTH2_AUDIENCE,
    OKTA_OAUTH2_CLIENT_ID,
    OKTA_OAUTH2_CLIENT_SECRET,
    OKTA_OAUTH2_MANAGEMENT_API_TOKEN,
    SPRING_MAIL_USERNAME,
    SPRING_MAIL_PASSWORD,
    OPENAI_TOKEN,
    STRIPE_PK,
    STRIPE_SK,
    WEATHER_API_KEY
}